import "./globals.css";
import Link from 'next/link';
import NavLink from '@/components/NavLink';

export const metadata = {
  title: "Recipe App",
  description: "Generated by jms",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <header>
          <nav>
            <div className="nav-container">
              <h1>레시피 앱</h1>
              <ul className="nav-menu">
                <li><NavLink href="/">홈</NavLink></li>
                <li><NavLink href="/list">레시피 목록</NavLink></li>
                <li><NavLink href="/create">레시피 작성</NavLink></li>
              </ul>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
