import "./globals.css";
import Link from 'next/link';

export const metadata = {
  title: "Recipe App",
  description: "Generated by jms",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <header>
          <nav>
            <div className="nav-container">
              <h1>레시피 앱</h1>
              <ul className="nav-menu">
                <li><Link href="/">홈</Link></li>
                <li><Link href="/recipes">레시피 목록</Link></li>
                <li><Link href="/create">레시피 작성</Link></li>
              </ul>
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
